spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.datasource.url=jdbc:postgresql://ep-cold-firefly-a5191315-pooler.us-east-2.aws.neon.tech/devopsify
spring.datasource.username=devopsify_owner
spring.datasource.password=npg_NWBzqvCnl5h2


#jdbc:postgresql://localhost:5432/devopsify
#?user=devopsify_owner&password=npg_NWBzqvCnl5h2&sslmode=require